<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => bcrypt('admin'),
                'role' => "Admin",
                'contact' => 9397240087,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Juan Dela Cruz',
                'email' => 'doctor@gmail.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 9947658892,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'John Doe',
                'email' => 'patient@gmail.com',
                'password' => bcrypt('patient'),
                'role' => "Patient",
                'contact' => 9767582122,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Ethan Johnson',
                'email' => 'patient1@gmail.com',
                'password' => bcrypt('patient'),
                'role' => "Patient",
                'contact' => 9345678123,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Olivia Parker',
                'email' => 'patient2@gmail.com',
                'password' => bcrypt('patient'),
                'role' => "Patient",
                'contact' => 9456789231,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Liam Thompson',
                'email' => 'patient3@gmail.com',
                'password' => bcrypt('patient'),
                'role' => "Patient",
                'contact' => 9832451760,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Sophia Rodriguez',
                'email' => 'patient4@gmail.com',
                'password' => bcrypt('patient'),
                'role' => "Patient",
                'contact' => 9721345698,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Noah Martinez',
                'email' => 'patient5@gmail.com',
                'password' => bcrypt('patient'),
                'role' => "Patient",
                'contact' => 9567892310,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Emma Anderson',
                'email' => 'patient6@gmail.com',
                'password' => bcrypt('patient'),
                'role' => "Patient",
                'contact' => 9901234567,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Charlotte Jones',
                'email' => 'charlotte.jones@example.com',
                'password' => bcrypt('password'),
                'role' => "Patient",
                'contact' => 8934567120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Ava Williams',
                'email' => 'ava.williams@example.com',
                'password' => bcrypt('password'),
                'role' => "Patient",
                'contact' => 7893214560,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'William Miller',
                'email' => 'william.miller@example.com',
                'password' => bcrypt('password'),
                'role' => "Patient",
                'contact' => 6782135490,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Mia Brown',
                'email' => 'mia.brown@example.com',
                'password' => bcrypt('password'),
                'role' => "Patient",
                'contact' => 5671098321,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Dr. Olivia Jones',
                'email' => 'doctor.jones@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 5432198760,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Dr. William Miller',
                'email' => 'doctor.miller@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 4321087659,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Dr. Mia Garcia',
                'email' => 'doctor.garcia@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 3210976548,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Dr. Michael Brown',
                'email' => 'doctor.brown@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 2109865437,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Dr. Isabella Hernandez',
                'email' => 'doctor.hernandez@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 1098754326,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Dr. James Moore',
                'email' => 'doctor.moore@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 9876543215,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Dr. Emily Lopez',
                'email' => 'doctor.lopez@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 8765432104,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Dr. Benjamin Lewis',
                'email' => 'doctor.lewis@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 7654321093,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'Dr. Ashley Robinson',
                'email' => 'doctor.robinson@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 6543210982,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Dr. David Walker',
                'email' => 'doctor.walker@example.com',
                'password' => bcrypt('doctor'),
                'role' => "Doctor",
                'contact' => 5432109871,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'Michael Garcia',
                'email' => 'michael.garcia@example.com',
                'password' => bcrypt('password'),
                'role' => "Patient",
                'contact' => 4560987213,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Isabella Hernandez',
                'email' => 'isabella.hernandez@example.com',
                'password' => bcrypt('password'),
                'role' => "Patient",
                'contact' => 3459876102,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'James Moore',
                'email' => 'james.moore@example.com',
                'password' => bcrypt('password'),
                'role' => "Patient",
                'contact' => 2348765091,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
